# Generated by Django 4.2.15 on 2025-08-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Other', 'Other')], default='Indian', max_length=50),
        ),
    ]
